export const REQUEST_FEATURED = 'REQUEST_FEATURED';
export const RECEIVE_FEATURED = 'RECEIVE_FEATURED';

export const REQUEST_GENRES = 'REQUEST_GENRES';
export const RECEIVE_GENRES = 'RECEIVE_GENRES';

export const REQUEST_NEW = 'REQUEST_NEW';
export const RECEIVE_NEW = 'RECEIVE_NEW';

export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';

export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';

export const REQUEST_RECENT_CONTENT = 'REQUEST_RECENT_CONTENT';
export const RECEIVE_RECENT_CONTENT = 'RECEIVE_RECENT_CONTENT';

export const REQUEST_DISCOVER = 'REQUEST_DISCOVER';
export const RECEIVE_DISCOVER = 'RECEIVE_DISCOVER';

export const REQUEST_USER_PLAYLIST = 'REQUEST_USER_PLAYLIST';
export const RECEIVE_USER_PLAYLIST = 'RECEIVE_USER_PLAYLIST';
